### ISSUE TITLE
please upload the source code so i can 100% trust this ok

### ISSUE THREAD

**Issue by ch0n-arch** [FloppyDolphin57/HorionDebugInjector#10]

**Comment by FloppyDolphin57** [comment]
Unobfuscated already, only takes a few brain cells to read everyine of code

**Comment by Aeroverra** [comment]
You can decompile it to an extent but can't be reversed completely. Your hesitation to release the code is a red flag itself.

**Comment by FloppyDolphin57** [comment]
> You can decompile it to an extent but can't be reversed completely. Your hesitation to release the code is a red flag itself.

Yes you actually can... It's coded in c# it can be decompiled back to original source.
