### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by InsanityMC** [FloppyDolphin57/HorionDebugInjector#16]
Everytime I inject it crashs/my minecraft  idk how to fix

**Comment by FloppyDolphin57** [comment]
You're on minecraft 1.16.210

**Comment by ekko95** [comment]
> You're on minecraft 1.16.210

is it not able to work on that version?

**Comment by chunkbanned** [comment]
> > You're on minecraft 1.16.210
> 
> is it not able to work on that version?

Yes, as it says in the "Help" tab of the injector, Horion and BadMan are for 1.16.201.

**Comment by InsanityMC** [comment]
Are u updating it ??
