### ISSUE TITLE
is there a way to open the hacks in the new version?

### ISSUE THREAD

**Issue by thunderpickle** [FloppyDolphin57/HorionDebugInjector#17]
is there a way are you working to break the patch or is it over?

**Comment by FloppyDolphin57** [comment]
no

**Comment by ndawg39** [comment]
cab i use is in 1.15.210

**Comment by ndawg39** [comment]
1.16.210

**Comment by thunderpickle** [comment]
the owner already said no
why u ask also I think someone will break the patch

**Comment by chunkbanned** [comment]
> 1.16.210

No, you cannot use it in 1.16.210.
![image](https://user-images.githubusercontent.com/59180376/111996863-595ef680-8b12-11eb-9dc6-7a49acf31ad3.png)
