### ISSUE TITLE
update to 1.16.220

### ISSUE THREAD

**Issue by lol435826** [FloppyDolphin57/HorionDebugInjector#18]
when will it be updated?

**Comment by FloppyDolphin57** [comment]
🤦‍♂️

**Comment by MelihGMC2** [comment]
HorionDebugInjector actually injects the latest horion branch, so when horion gets updated to 1.16.221 HorionDebugInjector will also update to 1.16.221. No one knows when it will get updated to 1.16.221 so stay patient
