### ISSUE TITLE
this is 100% a backdoor i have proof right here

### ISSUE THREAD

**Issue by ch0n-arch** [FloppyDolphin57/HorionDebugInjector#8]
![Capture](https://user-images.githubusercontent.com/66013293/107092421-6a4ce600-67b8-11eb-9513-1ed98fe0ed48.PNG)

**Comment by Drosh23** [comment]
my norton detected it as backdoor aswell, tried on other antiviruses and the other came positive aswell.

**Comment by Drosh23** [comment]
actually nvm the new release is good and not a virus

**Comment by due282** [comment]
tets
